# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.npm

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

  # js tests
  - nvm use $NODE_VERSION
  - cd vue
  - npm run test

scala:
  - 2.11.7

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=7.2.0

install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g npm@latest
  - cd vue
  - npm install
  - cd ..

notifications:
  email:
    - tanana@email.ru