# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.npm

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.npm -name "*.lock" | xargs rm

  # js tests
  - runJsTests.sh

scala:
  - 2.11.7

jdk:
  - oraclejdk8

node_js:
  - "7.2.0"

install: "cd vue;npm install"

notifications:
  email:
    - tanana@email.ru